### ISSUE TITLE
Package installs files in unexpected location

### ISSUE THREAD

**Issue by ameihm0912** [trink/streaming_algorithms#2]
@trink just making a quick note of this here,

It seems with the default build this ends up in /usr/lib64 where LSB extensions end up in /usr/lib; not immediately obvious why but I had to adjust some configuration files to look in the alternate location so there may be an inconsistency somewhere

**Comment by trink** [comment]
Hmm, yeah lib64 is actually the correct location for x64 but yeah they should be consistent one way or the other.  The nice thing about putting them in lib is the hindsight.cfg is consistent between debian and redhat.

**Comment by trink** [comment]
2f3f7e55dafec6dd00babdbf7bcb535184b1c666
Standardize the lua modules to `lib` for consistency.  The standalone library will still go the the official lib64 location.
